services:
  pgvector:
    image: ankane/pgvector:latest  # Use the pgvector-enabled PostgreSQL image
    container_name: pgvector-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust  
    volumes:
      - pgdata:/var/lib/postgresql/data  
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  
    ports:
      - "5432:5432"

volumes:
  pgdata:
